feat(pull): add menu for empty mode

diff --git a/dist/gitb b/dist/gitb
--- a/dist/gitb
+++ b/dist/gitb
@@ -1522,23 +1522,23 @@ function rebase_conflicts {
 
 ### Main function
 # $1: mode
-    # <empty> - pull current branch using default merge strategy
+    # <empty>: fetch current branch and ask about strategy
     # fetch: just fetch current branch
     # all: fetch all
     # upd: run git remote update to fetch all branches
     # ffonly: fast forward only
     # merge: pull current branch using default merge strategy
     # rebase: pull current branch using rebase or fast forward if it is possible
-    # interactive: pull current branch using interactive rebase
+    # interactive: pull current branch using interactive rebase with --autosquash
 function pull_script {
     case "$1" in
         fetch|fe)           fetch="true";;
         all|fa)             fetch="true"; all="true";;
         upd|u)              update="true";;
         ffonly|ff)          ffonly="true";;
-        merge|m)            ;; # default mode
+        merge|m)            merge="true";;
         rebase|r)           rebase="true";;
-        interactive|i|ri)   rebase="true"; interactive="true";;
+        interactive|ri|rs)  rebase="true"; interactive="true";;
         help|h)             help="true";;
         *)
             wrong_mode "pull" $1
@@ -1548,21 +1548,22 @@ function pull_script {
         echo -e "usage: ${YELLOW}gitb pull${ENDCOLOR}"
         echo
         echo -e "${YELLOW}Available modes${ENDCOLOR}"
-        echo -e "<empty>\t\t\tFetch current branch and then merge changes with conflicts fixing"
+        echo -e "<empty>\t\t\tFetch current branch, try to fast-forward or ask about strategy"
         echo -e "fetch|fe\t\tFetch current branch without merge"    
         echo -e "all|fa\t\t\tFetch all without merge"
         echo -e "upd|u\t\t\tRun git remote update to fetch all branches"
         echo -e "ffonly|ff\t\tFetch and then merge in fast forward only mode"
-        echo -e "merge|m\t\t\tFetch current branch and then merge it (default mode)"
+        echo -e "merge|m\t\t\tFetch current branch and then merge it"
         echo -e "rebase|r\t\tFetch current branch and then rebase"
-        echo -e "interactive|ri|i\tFetch current branch and then rebase in interactive mode"
+        echo -e "interactive|ri|rs\tFetch current branch and then rebase in interactive mode with --autosquash"
         echo -e "help|h\t\t\tShow this help"
         exit
     fi
 
-    mode="merge"
     if [ -n "$rebase" ]; then
         mode="rebase"
+    elif [ -n "$merge" ]; then
+        mode="merge"
     fi
 
     ### Print header
@@ -1581,6 +1582,8 @@ function pull_script {
         fi
     elif [ -n "${ffonly}" ]; then
         header_msg="$header_msg FAST FORWARD ONLY"
+    elif [ -n "${merge}" ]; then
+        header_msg="$header_msg MERGE"
     elif [ -n "${update}" ]; then
         header_msg="$header_msg REMOTE UPDATE"
     fi
@@ -1638,7 +1641,7 @@ function pull_script {
                 fi
                 echo
                 count=$(echo $commits | wc -l | sed 's/^ *//;s/ *$//')
-                echo -e "Your branch is behind ${YELLOW}$origin_name/$current_branch${ENDCOLOR} by ${BOLD}$count${ENDCOLOR} commits:"
+                echo -e "Your branch is behind ${YELLOW}$origin_name/$current_branch${ENDCOLOR} by ${BOLD}$count${ENDCOLOR} commits"
                 echo -e "$commits"
             else
                 echo -e "${GREEN}Already up to date${ENDCOLOR}"
@@ -1701,43 +1704,76 @@ function pull {
         return
     fi
 
-    if [ "$4" == "rebase" ]; then
-        rebase_branch $1 $2 "true" $interactive
-    else 
-        merge $1 $2 $3 "pull" "true" $5
-    fi 
+    merge_output=$(git merge --ff-only $2/$1 2>&1)
+    merge_code=$?
 
-    ### Nothing to pull
-    if ([[ "$4" == "rebase" ]] && [[ "$rebase_output" == "" ]]) || [[ $merge_output == *"Already up to date"* ]]; then
-        if [ "$4" == "rebase" ]; then
-            echo
-        fi       
+    if [[ $merge_output == *"Already up to date"* ]]; then  
         echo -e "${GREEN}Already up to date${ENDCOLOR}"
         return
     fi
 
-    ### It will exit if critical error or resolve conflicts, so here we can get only in case of success
-    echo -e "${GREEN}Successful pull!${ENDCOLOR}"
-    echo
+    if [ $merge_code != 0 ] ; then
+        if [[ $merge_output != *"possible to fast-forward"* ]]; then
+            echo -e "${RED}Cannot pull! Error message:${ENDCOLOR}"
+            echo "$merge_output"
+            exit $merge_code
+        fi
 
-    if [ "$fetch_output" != "" ]; then
-        echo -e "$fetch_output"
-        echo -e "Origin is ahead of local by this commits:"
-        echo -e $(commit_list 999 "tab" HEAD..$2/$1)
+        commits=$(commit_list 999 "tab" HEAD..$origin_name/$current_branch)
+        count=$(echo -e "$commits" | wc -l | sed 's/^ *//;s/ *$//')
+
+        echo -e "Your branch is behind ${YELLOW}$origin_name/$current_branch${ENDCOLOR} by ${BOLD}$count${ENDCOLOR} commits"
+        echo -e "$commits"
         echo
+
+        mode=$4
+        if [ "$4" == "merge" ]; then
+            echo -e "${YELLOW}Merging...${ENDCOLOR}"
+            choice="1"
+        elif [ "$4" == "rebase" ]; then
+            echo -e "${YELLOW}Rebasing...${ENDCOLOR}"
+            choice="2"
+        else
+            echo -e "${RED}Cannot fast forward!${ENDCOLOR} Choose an option:"
+            echo -e "1. ${BLUE}Merge.${ENDCOLOR} It saves commit's timeline, but creates a merge commit with message:"
+            echo -e "\t\t${YELLOW}Merge remote-tracking branch '$origin_name/$current_branch' into $current_branch${ENDCOLOR}"
+            echo -e "2. ${BLUE}Rebase.${ENDCOLOR} It takes all new local commits and places them on top of the remote branch"
+
+            read -n 1 -s choice
+            re='^[12]+$'
+            if ! [[ $choice =~ $re ]]; then
+                exit 0
+            fi
+        fi
+
+        echo
+
+        if [ "$choice" == "1" ]; then
+            merge $1 $2 $3 "pull" "true" $5
+            mode="merge"
+            if [ $merge_code != 0 ] ; then
+                echo
+           fi
+        else 
+           rebase_branch $1 $2 "true" $interactive $interactive
+           mode="rebase"
+           if [ $rebase_code != 0 ] ; then
+                echo
+           fi
+        fi
     fi
 
-    commit_hash=$(git rev-parse HEAD)
-    echo -e "${BLUE}[$current_branch ${commit_hash::7}]${ENDCOLOR}"
-    echo -e "${YELLOW}$(git log -1 --pretty=%B | cat)${ENDCOLOR}"
-    echo
+    echo -e "${GREEN}Successfully pulled with $mode!${ENDCOLOR}"
 
-    if [ "$4" == "rebase" ] ; then 
-        echo "$rebase_output"
-    else
+    if [ "$mode" == "merge" ] ; then 
+        echo
         ### Merge without conflicts
         if [ $merge_code == 0 ] ; then
-            changes=$(echo "$merge_output" | tail -n +2)
+            if [[ $merge_output == *"made by the"* ]]; then
+                changes=$(echo "$merge_output" | tail -n +3)
+            else
+                changes=$(echo "$merge_output" | tail -n +2)
+            fi
             if [[ -n "$changes" ]]; then
                 print_changes_stat "$changes"
             fi
