feat(global): working

diff --git a/dist/gitb b/dist/gitb
--- a/dist/gitb
+++ b/dist/gitb
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+### Main script for running gitbasher
+
+#!/usr/bin/env bash
+
 ### Consts for colors
 RED="\e[31m"
 GREEN="\e[32m"
@@ -39,6 +43,21 @@ function get_config_value {
         fi
     fi
     echo -e "$value"
+}
+
+
+### Function sets git config value
+# $1: name
+# $2: value
+# $3: global flag
+# Returns: value
+function set_config_value {
+    if [ -z $3 ]; then
+        git config --local --add $1 "$2"
+    else
+        git config --global --add $1 "$2"
+    fi
+    echo "$2"
 }
 
 
@@ -96,13 +115,16 @@ function check_code {
 
 ### Function asks user to enter yes or no, it will exit if user answers 'no'
 # $1: what to write in console on success
+# $2: flag no echo
 function yes_no_choice {
     while [ true ]; do
         read -n 1 -s choice
         if [ "$choice" == "y" ]; then
             if [ -n "$1" ]; then
                 echo -e "${YELLOW}$1${ENDCOLOR}"
-                echo
+                if [ -z $2 ]; then
+                    echo
+                fi
             fi
             return
         fi
@@ -391,7 +413,7 @@ function list_branches {
     for index in "${!branches_with_info_first_main[@]}"
     do
         branch=$(escape "${branches_first_main[index]}" "/")
-        if [[ "$1" == "remote" ]]; then
+        if [[ "$1" == "remote" ]] && [[ "$branch" != "origin"* ]]; then
             branch="$origin_name\/$branch"
         fi
         branch_line=$(sed "1,/${branch}/ s/${branch}/${GREEN_ES}${branch}${ENDCOLOR_ES}/" <<< ${branches_with_info_first_main[index]})
@@ -727,36 +749,132 @@ function pull {
 
 ### Script for configurate gitbasher
 # Read README.md to get more information how to use it
-# Use this script only with gitbasher
+# Use this script only with gitbasher because it is using global variables
 
+
+### Get configuration from git config
 main_branch=$(get_config_value gitbasher.branch "$main_branch")
 sep=$(get_config_value gitbasher.sep "/")
 editor=$(get_config_value core.editor "vim")
 
+### Is this is a first run of gitbasher in this project?
 is_first=$(get_config_value gitbasher.isfirst "true")
-git config --local --add gitbasher.isfirst "false"
+set_config_value gitbasher.isfirst false > /dev/null
 
 
+### Function asks user to select default gitbasher branch
 function set_main_branch {
-    echo "A"
-    # fetch branches
-    # select main branch
-    # ask for global
-    # set to cfg and var
+    echo -e "${YELLOW}Fetching remote branches...${ENDCOLOR}"
+    echo
+
+    fetch_output=$(git fetch 2>&1)
+    fetch_code=$?
+    if [ $fetch_code -ne 0 ] ; then
+        echo -e "${RED}Cannot fetch remote!${ENDCOLOR}"
+        echo -e "${fetch_output}"
+        exit $fetch_code
+    fi
+
+    prune_output=$(git remote prune $origin_name 2>&1)
+
+    echo -e "Current gitbasher default branch: ${YELLOW}$main_branch${ENDCOLOR}"
+    echo
+    
+    echo -e "${YELLOW}Select a branch to make it default in gitbasher${ENDCOLOR}"
+    choose_branch "remote"
+
+    echo 
+
+    main_branch=$(set_config_value gitbasher.branch $branch_name)
+    echo -e "${GREEN}Set '${branch_name}' as default gitbasher branch in '${project_name}' repo${ENDCOLOR}"
+
+    echo -e "Do you want to set it globally for all projects (y/n)?"
+    yes_no_choice "\nSet '${branch_name}' globally" "true"
+    main_branch=$(set_config_value gitbasher.branch $branch_name "true")
 }
 
+
+### Function asks user to select branch name separator
 function set_sep {
-    echo "A"
-    # select sep from provided variants
-    # ask for global
-    # set to cfg and var
+    echo -e "${YELLOW}Select a branch name separator${ENDCOLOR}"
+    echo -e "Separator is a symbol between type and name, e.g. ${YELLOW}name${sep}name${ENDCOLOR}"
+    echo -e "Current separator: ${YELLOW}$sep${ENDCOLOR}"
+    echo -e "1. type${YELLOW}/${ENDCOLOR}name"
+    echo -e "2. type${YELLOW}_${ENDCOLOR}name"
+    echo -e "3. type${YELLOW}-${ENDCOLOR}name"
+    echo -e "4. type${YELLOW}.${ENDCOLOR}name"
+    echo -e "5. type${YELLOW},${ENDCOLOR}name"
+    echo -e "6. type${YELLOW}+${ENDCOLOR}name"
+    echo -e "7. type${YELLOW}=${ENDCOLOR}name"
+    echo -e "8. type${YELLOW}@${ENDCOLOR}name"
+    echo "0. Exit without changes"
+    
+    declare -A seps=(
+            [1]="/"
+            [2]="_"
+            [3]="-"
+            [4]="."
+            [5]=","
+            [6]="+"
+            [7]="="
+            [8]="@"
+        )
+
+    while [ true ]; do
+        read -n 1 -s choice
+
+        if [ "$choice" == "0" ]; then
+            exit
+        fi
+
+        re='^[0-9]+$'
+        if ! [[ $choice =~ $re ]]; then
+            continue
+        fi
+
+        new_sep="${seps[$choice]}"
+        if [ -n "$new_sep" ]; then
+            break
+        fi
+    done
+
+    echo
+
+    sep=$(set_config_value gitbasher.sep $new_sep)
+    echo -e "${GREEN}Set '${sep}' as branch name separator in '${project_name}' repo${ENDCOLOR}"
+
+    echo -e "Do you want to set it globally for all projects (y/n)?"
+    yes_no_choice "\nSet '${sep}' globally" "true"
+    sep=$(set_config_value gitbasher.sep $branch_name $new_sep)
 }
 
+
+### Function asks user to enter editor for commit messages
 function set_editor {
-    echo "A"
-    # enter editor
-    # ask for global and say that this is a git setting
-    # set to cfg and var
+    echo -e "${YELLOW}Enter an editor for commit messages${ENDCOLOR}"
+    echo -e "Enter the bin name of editor to run for creating commit messages (e.g. 'vim' or 'nano')"
+    echo -e "It will override ${YELLOW}core.editor${ENDCOLOR} git config value, leave it blank to exit without changes"
+    echo -e "Current editor: ${YELLOW}${editor}${ENDCOLOR}"
+    read -p "Editor: " choice
+
+    if [ "$choice" == "" ]; then
+        exit
+    fi
+
+    echo
+
+    which_output=$(which $choice)
+    if [ "${which_output}" == *"not found"* ] || [ "${which_output}" == "" ]; then
+        echo -e "${RED}Binary '${choice}' not found!${ENDCOLOR}"
+        exit
+    fi
+
+    editor=$(set_config_value core.editor $choice)
+    echo -e "${GREEN}Use editor '$editor' located at '$which_output'${ENDCOLOR}"
+
+    echo -e "Do you want to set it globally for all projects (y/n)?"
+    yes_no_choice "\nSet '${editor}' globally" "true"
+    sep=$(set_config_value core.editor $branch_name $new_sep)
 }
 
 
@@ -768,25 +886,32 @@ function set_editor {
     # editor: set commit message editor
 function config_script {
     case "$1" in
-        main|master)  main="true";;
-        sep)          sep="true";;
-        editor)       editor="true";;
+        main|master)  set_main_cfg="true";;
+        separator|sep)          set_sep_cfg="true";;
+        editor)       set_editor_cfg="true";;
     esac
 
-    if [ -z $main ]; then
+    if [ "$set_main_cfg" == "true" ]; then
         set_main_branch
         exit
     fi
 
-    if [ -z $sep ]; then
+    if [ "$set_sep_cfg" == "true" ]; then
         set_sep
         exit
     fi
 
-    if [ -z $editor ]; then
+    if [ "$set_editor_cfg" == "true" ]; then
         set_editor
         exit
     fi
+
+    echo -e "usage: ${YELLOW}gitb config <name>${ENDCOLOR}"
+    echo
+    echo "Available names for configuration:"
+    echo -e "${YELLOW}main:${ENDCOLOR}\tupdate gitbasher's default branch (not remote git repo!)"
+    echo -e "${YELLOW}sep:${ENDCOLOR}\tupdate separator between type and name in branch"
+    echo -e "${YELLOW}editor:${ENDCOLOR}\tupdate text editor for commit messages"
 }
 
 #!/usr/bin/env bash
@@ -1007,7 +1132,7 @@ function commit_script {
     echo "7. ci:        changes to CI configuration files and scripts"
     echo "8. chore:     maintanance and housekeeping"
     echo "9. docs:      documentation only changes"
-    echo "0. EXIT without changes"
+    echo "0. Exit without changes"
 
     declare -A types=(
         [1]="feat"
@@ -2140,6 +2265,8 @@ function tag_script {
     push_tag $tag_name
 }
 
+project_name="$(get_repo_name)"
+
 
 ### Cannot use bash version less than 4 because of many features that was added to language in that version
 if ((BASH_VERSINFO[0] < 4)); then
@@ -2152,7 +2279,6 @@ exit 1;
 fi
 
 if [ $is_first == "true" ]; then
-project_name="$(get_repo_name)"
 echo -e "${GREEN}Thank for using gitbasher in project '$project_name'${ENDCOLOR}"
 echo -e "Current settings:"
 echo -e "tmain: '$main_branch'"
@@ -2172,7 +2298,7 @@ declare -a branch=("branch" "b" "br" "bh" "bch" "bra")
 declare -a tag=("tag" "t" "tg" "release")
 declare -a config=("config" "cfg" "conf" "settings")
 
-declare -a scripts=("commit" "push" "pull" "merge" "branch" "tag")
+declare -a scripts=("commit" "push" "pull" "merge" "branch" "tag" "config")
 
 function get_script_name {
 for script in "${scripts[@]}"; do
@@ -2188,19 +2314,19 @@ done
 
 
 script_to_run=$(get_script_name $1)
-if [ $script_to_run == "commit" ]; then
+if [ "$script_to_run" == "commit" ]; then
 commit_script $2
-elif [ $script_to_run == "push" ]; then
+elif [ "$script_to_run" == "push" ]; then
 push_script $2
-elif [ $script_to_run == "pull" ]; then
+elif [ "$script_to_run" == "pull" ]; then
 pull_script $2
-elif [ $script_to_run == "merge" ]; then
+elif [ "$script_to_run" == "merge" ]; then
 merge_script $2
-elif [ $script_to_run == "branch" ]; then
+elif [ "$script_to_run" == "branch" ]; then
 branch_script $2
-elif [ $script_to_run == "tag" ]; then
+elif [ "$script_to_run" == "tag" ]; then
 tag_script $2
-elif [ $script_to_run == "config" ]; then
+elif [ "$script_to_run" == "config" ]; then
 config_script $2
 fi
 
