fixup! chore: dev

diff --git a/dist/gitb b/dist/gitb
--- a/dist/gitb
+++ b/dist/gitb
@@ -946,7 +946,8 @@ function merge_commit {
     merge_error="false"
 
     ### Check if there are files with conflicts
-    IFS=$'\n' read -rd '' -a files_with_conflicts_new <<<"$(grep --files-with-matches -r -E "[<=>]{7} HEAD" .)"
+    files_with_conflicts_one_line="$(tr '\n' ' ' <<< "$2")"
+    IFS=$'\n' read -rd '' -a files_with_conflicts_new <<<"$(grep --files-with-matches -r -E "[<=>]{7} HEAD" $files_with_conflicts_one_line)"
     number_of_conflicts=${#files_with_conflicts_new[@]}
     if [ $number_of_conflicts -gt 0 ]; then
         echo
@@ -1155,6 +1156,8 @@ function rebase_branch {
 
     echo -e "${RED}Cannot rebase! There are conflicts${ENDCOLOR}"
     rebase_conflicts $rebase_output
+
+    # TODO: success
 }
 
 ### Function pulls provided branch, handles errors and makes a merge
@@ -1165,8 +1168,8 @@ function rebase_conflicts {
     echo -e "${YELLOW}You should resolve conflicts manually${ENDCOLOR}"
     echo -e "After resolving, select an option to continue:"
     echo -e "1. Add changes and continue: ${YELLOW}git rebase --continue${ENDCOLOR}"
-    echo -e "2. Skip this commit: ${YELLOW}git rebase --skip${ENDCOLOR}"
-    echo -e "3. Open editor to change rebase plan: ${YELLOW}git rebase --edit-todo${ENDCOLOR}"
+    echo -e "2. Open editor to change rebase plan: ${YELLOW}git rebase --edit-todo${ENDCOLOR}"
+    echo -e "3. Skip this commit (this will throw away this commit from history!): ${YELLOW}git rebase --skip${ENDCOLOR}"
     echo -e "4. Abort rebase and return to the original state: ${YELLOW}git rebase --abort${ENDCOLOR}"
     echo -e "Press any another key to exit from this script ${BOLD}without${NORMAL} rebase abort"
 
@@ -1187,9 +1190,11 @@ function rebase_conflicts {
         current_step=$(echo $status | sed -n 's/.*Last command done (\([0-9]*\) command done):/\1/p')
         total_steps=$(echo $status | sed -n 's/.*Next commands to do (\([0-9]*\) remaining commands):/\1/p')
         commit_name=$(echo $status | head -n 3 | tail -n 1)
+        files=$(echo $status | sed -n '/^Unmerged paths:/,/^$/p' | sed '/^Unmerged paths:/d;/^$/d;/^ *(/d')
 
-
-        # git status
+        echo
+        echo -e "${YELLOW}Step $current_step/$total_steps:${ENDCOLOR} $commit_name"
+        echo -e "$files"
 
         read -n 1 -s choice
 
@@ -1199,7 +1204,8 @@ function rebase_conflicts {
         fi
 
         if [ "$choice" == "1" ]; then
-            IFS=$'\n' read -rd '' -a files_with_conflicts_new <<<"$(grep --files-with-matches -r -E "[<=>]{7} HEAD" .)"
+            files_with_conflicts_one_line="$(tr '\n' ' ' <<< "$files_with_conflicts")"
+            IFS=$'\n' read -rd '' -a files_with_conflicts_new <<<"$(grep --files-with-matches -r -E "[<=>]{7} HEAD" $files_with_conflicts_one_line)"
             number_of_conflicts=${#files_with_conflicts_new[@]}
             if [ $number_of_conflicts -gt 0 ]; then
                 echo
@@ -1215,22 +1221,32 @@ function rebase_conflicts {
                 continue
             fi
 
-            files_with_conflicts_one_line="$(tr '\n' ' ' <<< "$files_with_conflicts")"
             git add $files_with_conflicts_one_line
-            git -c core.editor=true rebase --continue
 
-            ## TODO: handle
+            rebase_output=$(git -c core.editor=true rebase --continue)
+            rebase_code=$?
+
+            if [[ $rebase_output == *"Successfully rebased"* ]]; then
+                return
+            fi
+
+            if [[ $rebase_output != *"CONFLICT"* ]]; then
+                echo -e "${RED}Cannot rebase! Error message:${ENDCOLOR}"
+                echo "$rebase_output"
+                exit $rebase_code
+            fi
         fi
 
         if [ "$choice" == "2" ]; then
+            git rebase --edit-todo
+            ## TODO: handle todo
+        fi
+
+        if [ "$choice" == "3" ]; then
             git rebase --skip
             ## TODO: handle skip
         fi
 
-        if [ "$choice" == "3" ]; then
-            git rebase --edit-todo
-            ## TODO: handle todo
-        fi
 
         if [ "$choice" == "4" ]; then
             echo
