feat: add stash management functionality

diff --git a/dist/gitb b/dist/gitb
--- a/dist/gitb
+++ b/dist/gitb
@@ -3292,6 +3292,273 @@ function reset_script {
     git_status
     exit
 }
+function select_files_for_stash {
+    echo -e "${YELLOW}Select files to stash:${ENDCOLOR}"
+    echo
+    git_status
+    echo
+    echo -e "Enter file patterns or paths to stash (like ${BOLD}git add${ENDCOLOR} command)"
+    echo "Leave it blank to exit without changes"
+    while [ true ]; do
+        read -p "$(echo -n -e "${BOLD}files to stash${ENDCOLOR} ")" -e git_add
+        git_add=$(echo "$git_add" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e "s/^'//" -e "s/'$//")
+        if [ "$git_add" == "" ]; then
+            exit
+        fi
+        test_result=$(git add --dry-run $git_add 2>&1)
+        test_code=$?
+        if [ $test_code -eq 0 ] && [ -n "$test_result" ]; then
+            break
+        else
+            if [[ "$test_result" == *"did not match any files"* ]] && [[ "$git_add" != *"*" ]]; then
+                git_add_with_star="${git_add}*"
+                echo -e "${YELLOW}Trying with wildcard:${ENDCOLOR} ${BOLD}$git_add_with_star${ENDCOLOR}"
+                test_result_star=$(git add --dry-run $git_add_with_star 2>&1)
+                if [ $? -eq 0 ] && [ -n "$test_result_star" ]; then
+                    git_add="$git_add_with_star"
+                    break
+                else
+                    echo -e "${RED}No changed files match pattern: $git_add_with_star${ENDCOLOR}"
+                    echo
+                fi
+            else
+                echo -e "${RED}No changed files match pattern: $git_add${ENDCOLOR}"
+                echo
+            fi
+        fi
+    done
+}
+function list_stashes {
+    IFS=$'\n' read -rd '' -a stashes_info <<<"$(git stash list --pretty=format:"${YELLOW_ES}%gd${ENDCOLOR_ES} | %s | ${BLUE_ES}%cr${ENDCOLOR_ES}")"
+    IFS=$'\n' read -rd '' -a stashes_refs <<<"$(git stash list --pretty=format:"%gd")"
+    if [ ${#stashes_info[@]} -eq 0 ]; then
+        echo -e "${GREEN}No stashes found${ENDCOLOR}"
+        return 1
+    fi
+    echo -e "${YELLOW}Available stashes:${ENDCOLOR}"
+    echo
+    for index in "${!stashes_info[@]}"; do
+        stash_line="${stashes_info[index]}"
+        formatted_line=$(echo "$stash_line" | sed 's/ | /\t/g')
+        echo -e "$(($index+1)). $formatted_line"
+    done
+    echo
+    return 0
+}
+function choose_stash {
+    if ! list_stashes; then
+        return 1
+    fi
+    if [ ${#stashes_refs[@]} -gt 9 ]; then
+        echo "00. Exit"
+    else
+        echo "0. Exit"
+    fi
+    echo
+    read_prefix="Select stash number: "
+    choose "${stashes_refs[@]}"
+    echo
+    selected_stash=$choice_result
+}
+function show_stash {
+    echo -e "${YELLOW}Stash details for $1${ENDCOLOR}"
+    echo
+    git stash show -p "$1"
+}
+function stash_script {
+    case "$1" in
+        select|sel)     select_mode="true";;
+        all)            all_mode="true";;
+        list|l)         list_mode="true";;
+        pop|p)          pop_mode="true";;
+        show|s)         show_mode="true";;
+        drop|d)         drop_mode="true";;
+        apply|a)        apply_mode="true";;
+        help|h)         help="true";;
+        *)
+            if [ -n "$1" ]; then
+                wrong_mode "stash" "$1"
+            fi
+            interactive="true"
+    esac
+    header_msg="GIT STASH"
+    if [ -n "${select_mode}" ]; then
+        header_msg="${YELLOW}$header_msg SELECT${ENDCOLOR}"
+    elif [ -n "${all_mode}" ]; then
+        header_msg="${YELLOW}$header_msg ALL${ENDCOLOR}"
+    elif [ -n "${list_mode}" ]; then
+        header_msg="${YELLOW}$header_msg LIST${ENDCOLOR}"
+    elif [ -n "${pop_mode}" ]; then
+        header_msg="${YELLOW}$header_msg POP${ENDCOLOR}"
+    elif [ -n "${show_mode}" ]; then
+        header_msg="${YELLOW}$header_msg SHOW${ENDCOLOR}"
+    elif [ -n "${drop_mode}" ]; then
+        header_msg="${RED}$header_msg DROP${ENDCOLOR}"
+    elif [ -n "${apply_mode}" ]; then
+        header_msg="${YELLOW}$header_msg APPLY${ENDCOLOR}"
+    else
+        header_msg="${YELLOW}$header_msg${ENDCOLOR}"
+    fi
+    echo -e "${header_msg}"
+    echo
+    if [ -n "$help" ]; then
+        echo -e "usage: ${YELLOW}gitb stash <mode>${ENDCOLOR}"
+        echo
+        echo -e "${YELLOW}Available modes${ENDCOLOR}"
+        echo -e "<empty>\t\tShow interactive menu"
+        echo -e "select|sel\tSelect files to stash"
+        echo -e "all\t\tStash all changes"
+        echo -e "list|l\t\tList all stashes"
+        echo -e "pop|p\t\tPop from selected stash"
+        echo -e "show|s\t\tShow stash contents"
+        echo -e "apply|a\t\tApply selected stash without removing it"
+        echo -e "drop|d\t\tDrop selected stash"
+        echo -e "help|h\t\tShow this help"
+        exit
+    fi
+    if [ -n "$interactive" ]; then
+        echo -e "${YELLOW}What do you want to do?${ENDCOLOR}"
+        echo
+        echo "1. Select files to stash"
+        echo "2. Stash all changes"
+        echo "3. List all stashes"
+        echo "4. Pop from stash"
+        echo "5. Show stash contents"
+        echo "6. Apply stash (without removing)"
+        echo "7. Drop stash"
+        echo "0. Exit"
+        read -n 1 -s choice
+        echo
+        case "$choice" in
+            1) select_mode="true";;
+            2) all_mode="true";;
+            3) list_mode="true";;
+            4) pop_mode="true";;
+            5) show_mode="true";;
+            6) apply_mode="true";;
+            7) drop_mode="true";;
+            0) exit;;
+            *) echo -e "${RED}Invalid option${ENDCOLOR}"; exit 1;;
+        esac
+    fi
+    if [ -n "$select_mode" ]; then
+        select_files_for_stash
+        echo
+        echo -e "${YELLOW}Changed files to stash:${ENDCOLOR}"
+        files_to_stash=$(git add --dry-run $git_add 2>/dev/null | sed 's/^add /\t/' | sed "s/'//g")
+        echo -e "${GREEN}$files_to_stash${ENDCOLOR}"
+        echo
+        read -p "Enter stash message: " stash_message
+        if [ -z "$stash_message" ]; then
+            exit 0
+        fi
+        echo -e "${YELLOW}Stashing selected files...${ENDCOLOR}"
+        echo
+        result=$(git add $git_add 2>&1)
+        if [ $? -ne 0 ]; then
+            echo -e "${RED}Failed to stage files! Error:${ENDCOLOR}"
+            echo "$result"
+            exit 1
+        fi
+        stash_output=$(git stash push -m "$stash_message" --staged 2>&1)
+        stash_code=$?
+        if [ $stash_code -eq 0 ]; then
+            echo -e "${GREEN}Successfully stashed selected files!${ENDCOLOR}"
+            echo "$stash_output"
+        else
+            echo -e "${RED}Failed to stash files! Error:${ENDCOLOR}"
+            echo "$stash_output"
+            git restore --staged $git_add 2>/dev/null
+            exit $stash_code
+        fi
+    fi
+    if [ -n "$all_mode" ]; then
+        if git diff --quiet && git diff --cached --quiet; then
+            echo -e "${GREEN}No changes to stash${ENDCOLOR}"
+            exit
+        fi
+        read -p "Enter stash message: " stash_message
+        if [ -z "$stash_message" ]; then
+            exit 0
+        fi
+        echo -e "${YELLOW}Stashing all changes...${ENDCOLOR}"
+        echo
+        stash_output=$(git stash push -m "$stash_message" --include-untracked 2>&1)
+        stash_code=$?
+        if [ $stash_code -eq 0 ]; then
+            echo -e "${GREEN}Successfully stashed all changes!${ENDCOLOR}"
+            echo "$stash_output"
+        else
+            echo -e "${RED}Failed to stash changes! Error:${ENDCOLOR}"
+            echo "$stash_output"
+            exit $stash_code
+        fi
+    fi
+    if [ -n "$list_mode" ]; then
+        if ! list_stashes; then
+            exit
+        fi
+    fi
+    if [ -n "$pop_mode" ]; then
+        if ! choose_stash; then
+            exit 1
+        fi
+        echo -e "${YELLOW}Popping from stash $selected_stash...${ENDCOLOR}"
+        echo
+        pop_output=$(git stash pop "$selected_stash" 2>&1)
+        pop_code=$?
+        if [ $pop_code -eq 0 ]; then
+            echo -e "${GREEN}Successfully popped from stash!${ENDCOLOR}"
+            echo "$pop_output"
+        else
+            echo -e "${RED}Failed to pop from stash! Error:${ENDCOLOR}"
+            echo "$pop_output"
+            exit $pop_code
+        fi
+    fi
+    if [ -n "$show_mode" ]; then
+        if ! choose_stash; then
+            exit 1
+        fi
+        show_stash "$selected_stash"
+    fi
+    if [ -n "$apply_mode" ]; then
+        if ! choose_stash; then
+            exit 1
+        fi
+        echo -e "${YELLOW}Applying stash $selected_stash...${ENDCOLOR}"
+        echo
+        apply_output=$(git stash apply "$selected_stash" 2>&1)
+        apply_code=$?
+        if [ $apply_code -eq 0 ]; then
+            echo -e "${GREEN}Successfully applied stash!${ENDCOLOR}"
+            echo "$apply_output"
+        else
+            echo -e "${RED}Failed to apply stash! Error:${ENDCOLOR}"
+            echo "$apply_output"
+            exit $apply_code
+        fi
+    fi
+    if [ -n "$drop_mode" ]; then
+        if ! choose_stash; then
+            exit 1
+        fi
+        echo
+        echo -e "${RED}Are you sure you want to drop stash $selected_stash? This cannot be undone!${ENDCOLOR}"
+        echo -e "Do you want to continue (y/n)?"
+        yes_no_choice "Dropping stash"
+        drop_output=$(git stash drop "$selected_stash" 2>&1)
+        drop_code=$?
+        if [ $drop_code -eq 0 ]; then
+            echo -e "${GREEN}Successfully dropped stash!${ENDCOLOR}"
+            echo "$drop_output"
+        else
+            echo -e "${RED}Failed to drop stash! Error:${ENDCOLOR}"
+            echo "$drop_output"
+            exit $drop_code
+        fi
+    fi
+} 
 function project_status {
     echo -e "${YELLOW}$project_name${ENDCOLOR} | ${CYAN}$repo_url${ENDCOLOR}"
     echo
@@ -3329,10 +3596,11 @@ function print_help {
     msg="$msg\nmerge_m|me_Merge changes to the current branch"
     msg="$msg\nrebase_r|re|base_Rebase current branch"
     msg="$msg\nreset_res_Easy to use git reset"
+    msg="$msg\nstash_s|sta_Manage git stashes"
     msg="$msg\nconfig_cf|cfg|conf_Configurate gitbasher"
     msg="$msg\n_ _ _"
     msg="$msg\n${YELLOW}Command${ENDCOLOR}_\t${GREEN}Aliases${ENDCOLOR}_\t${BLUE}Description of ${BOLD}informational${NORMAL}${BLUE} commands${ENDCOLOR}"
-    msg="$msg\nstatus_s|st_Info about repo and changed files"
+    msg="$msg\nstatus_st_Info about repo and changed files"
     msg="$msg\nlog_l|lg_Open git log in a pretty format"
     msg="$msg\nreflog_rl|rlg_Open git reflog in a pretty format"
     msg="$msg\nlast-commit_lc|lastc_Show info about the last commit"
@@ -3381,6 +3649,9 @@ case "$1" in
     reset|res)
         reset_script $2
     ;;
+    stash|s|sta)
+        stash_script $2
+    ;;
     log|l|lg)
         gitlog
     ;;
@@ -3393,7 +3664,7 @@ case "$1" in
     last-ref|lr|lastr)
         last_ref
     ;;
-    status|s|st)
+    status|st)
         project_status
     ;;
     *)
