feat(commit): add scopes selector and colors

diff --git a/dist/gitb b/dist/gitb
--- a/dist/gitb
+++ b/dist/gitb
@@ -406,7 +406,7 @@ main_branch=$(get_config_value gitbasher.branch "$main_branch")
 sep=$(get_config_value gitbasher.sep "-")
 editor=$(get_config_value core.editor "vi")
 ticket_name=$(get_config_value gitbasher.ticket "")
-scopes=$(get_config_value gitbasher.scopes "logic model config logs")
+scopes=$(get_config_value gitbasher.scopes "")
 is_first=$(get_config_value gitbasher.isfirst "true")
 set_config_value gitbasher.isfirst false > /dev/null
 project_name="$(get_repo_name)"
@@ -522,10 +522,21 @@ function set_ticket {
 function set_scopes {
     echo -e "${YELLOW}Enter a list of predefined scopes${ENDCOLOR}"
     echo
-    echo -e "Current list of scopes: ${YELLOW}$scopes${ENDCOLOR}"
+    if [ "$scopes" == "" ]; then
+        echo -e "${YELLOW}Scopes list is not set${ENDCOLOR}"
+    else
+        echo -e "Current list of scopes: ${YELLOW}$scopes${ENDCOLOR}"
+    fi
     echo -e "Use only english letters and space as separator, maximum is 9 scopes"
+    echo -e "Enter 0 if you want to remove scopes"
     read -p "Scopes: " -e scopes_raw
     if [ "$scopes_raw" == "" ]; then
+        exit
+    fi
+    if [ "$scopes_raw" == "0" ]; then
+        git config --local --unset-all gitbasher.scopes
+        echo
+        echo -e "${GREEN}Scopes list removed from '${project_name}' repo${ENDCOLOR}"
         exit
     fi
     echo
@@ -535,6 +546,7 @@ function set_scopes {
         exit
     fi
     git config --local --replace-all gitbasher.scopes "$scopes_raw"
+    scopes="$scopes_raw"
     echo -e "${GREEN}Set '${scopes}' as a scopes list in '${project_name}' repo${ENDCOLOR}"
     echo
     echo -e "Do you want to set it ${YELLOW}globally${ENDCOLOR} for all projects (y/n)?"
@@ -1672,15 +1684,16 @@ function commit_script {
     if [ -n "${fast}" ]; then
         step="1"
     fi
-    echo -e "${YELLOW}Step ${step}.${ENDCOLOR} What type of changes do you want to commit?"
-    echo -e "1. feat:\tnew feature, logic change or performance improvement"
-    echo -e "2. fix:\t\tsmall changes, eg. bug fix"
-    echo -e "3. refactor:\tcode change that neither fixes a bug nor adds a feature, style changes"
-    echo -e "4. test:\tadding missing tests or changing existing tests"
-    echo -e "5. build:\tchanges that affect the build system or external dependencies"
-    echo -e "6. ci:\t\tchanges to CI configuration files and scripts"
-    echo -e "7. chore:\tmaintanance and housekeeping"
-    echo -e "8. docs:\tdocumentation changes"
+    echo -e "${YELLOW}Step ${step}.${ENDCOLOR} What ${YELLOW}type${ENDCOLOR} of changes do you want to commit?"
+    echo -e "Final meesage will be ${YELLOW}<type>${ENDCOLOR}(${BLUE}<scope>${ENDCOLOR}): ${BLUE}<summary>${ENDCOLOR}"
+    echo -e "1. ${BOLD}feat${ENDCOLOR}:\tnew feature, logic change or performance improvement"
+    echo -e "2. ${BOLD}fix${ENDCOLOR}:\t\tsmall changes, eg. bug fix"
+    echo -e "3. ${BOLD}refactor${ENDCOLOR}:\tcode change that neither fixes a bug nor adds a feature, style changes"
+    echo -e "4. ${BOLD}test${ENDCOLOR}:\tadding missing tests or changing existing tests"
+    echo -e "5. ${BOLD}build${ENDCOLOR}:\tchanges that affect the build system or external dependencies"
+    echo -e "6. ${BOLD}ci${ENDCOLOR}:\t\tchanges to CI configuration files and scripts"
+    echo -e "7. ${BOLD}chore${ENDCOLOR}:\tmaintanance and housekeeping"
+    echo -e "8. ${BOLD}docs${ENDCOLOR}:\tdocumentation changes"
     echo -e "9.  \t\twrite plain commit without type and scope"
     echo -e "0. Exit without changes"
     declare -A types=(
@@ -1716,24 +1729,57 @@ function commit_script {
     if [ -z "$is_empty" ]; then
         commit="$commit_type"
     fi
-    if ([ -z "$is_empty" ] && [ -z "$fast" ]) || [ -n "$scope" ]; then
+    if [ -z "$is_empty" ] && ([ -z "$fast" ] || [ -n "$scope" ]); then
         step="3"
         if [ -n "${fast}" ]; then
             step="2"
         fi
         echo
-        echo -e "${YELLOW}Step ${step}.${ENDCOLOR} Enter a scope of changes to provide an additional context"
-        echo -e "Final meesage will be ${YELLOW}${commit_type}(<scope>): <summary>${ENDCOLOR}"
+        echo -e "${YELLOW}Step ${step}.${ENDCOLOR} Enter a ${YELLOW}scope${ENDCOLOR} of changes to provide some additional context"
+        echo -e "Final meesage will be ${BLUE}${commit_type}${ENDCOLOR}(${YELLOW}<scope>${ENDCOLOR}): ${BLUE}<summary>${ENDCOLOR}"
         echo -e "Leave it blank to continue without scope or enter 0 to exit without changes"
-        read -p "$(echo -n -e "${TODO}<scope>:${ENDCOLOR} ")" -e commit_scope
+        if [ -n "$scopes" ]; then
+           IFS=' ' read -r -a scopes_array <<< "$scopes"
+           res=""
+           for i in "${!scopes_array[@]}"; do
+                res="$res$((i+1)). ${BOLD}${scopes_array[$i]}${ENDCOLOR}|"
+           done
+           echo -e "Select or enter: $(echo $res | column -ts'|')"            
+        fi
+        read -p "<scope>: " -n 1 -s commit_scope
         if [ "$commit_scope" == "0" ]; then
             git restore --staged $git_add
             exit
         fi
-        commit_scope=$(echo "$commit_scope" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
-        if [ "$commit_scope" != "" ]; then
-            commit="$commit($commit_scope): "
+        re='^[1-9a-zA-Z\-_\?\.<>]+$'
+        if [[ $commit_scope =~ $re ]]; then
+            re_number='^[1-9]+$'
+            if [[ $commit_scope =~ $re_number ]]; then
+                for i in "${!scopes_array[@]}"; do
+                    if [ "$((i+1))" == "$commit_scope" ]; then
+                        commit_scope="${scopes_array[$i]}"
+                        found="true"
+                        echo
+                        break
+                    fi
+                done
+            fi
+            if [ "$found" == "" ]; then
+                read -p "$commit_scope" -e commit_scope2
+                commit_scope="$commit_scope$commit_scope2"
+            fi
+            if [ "$commit_scope" != "" ]; then
+                if ! [[ $commit_scope =~ $re ]]; then
+                    echo
+                    echo -e "${RED}Invalid scope!${ENDCOLOR}"
+                    exit 1
+                fi
+                commit="$commit($commit_scope): "
+            else
+                commit="$commit: "
+            fi
         else
+            echo
             commit="$commit: "
         fi
     fi
@@ -1752,8 +1798,14 @@ function commit_script {
         step="4"
     fi
     echo
-    echo -e "${YELLOW}Step ${step}.${ENDCOLOR} Write a <summary> about your changes"
-    echo -e "Final meesage will be ${YELLOW}${commit}<summary>${ENDCOLOR}"
+    echo -e "${YELLOW}Step ${step}.${ENDCOLOR} Write a ${YELLOW}summary${ENDCOLOR} about your changes"
+    if [ -n "$is_empty" ]; then
+        echo -e "Final meesage will be ${YELLOW}<summary>${ENDCOLOR}"
+    elif [ "$commit_scope" == "" ]; then
+        echo -e "Final meesage will be ${BLUE}${commit_type}${ENDCOLOR}: ${YELLOW}<summary>${ENDCOLOR}"
+    else
+        echo -e "Final meesage will be ${BLUE}${commit_type}${ENDCOLOR}(${BLUE}${commit_scope}${ENDCOLOR}): ${YELLOW}<summary>${ENDCOLOR}"
+    fi
     echo -e "Leave it blank to exit without changes"
     if [ -n "$msg" ]; then
         commitmsg_file=".commitmsg__"
@@ -2556,6 +2608,7 @@ if [ $is_first == "true" ]; then
     print_configuration
     echo
     echo -e "You can change these settings by using ${YELLOW}gitb cfg <name>${ENDCOLOR}"
+    git config --local gitbasher.scopes "logic model config logs"
 fi
 case "$1" in
     commit|c|co|com)         
